### ISSUE TITLE
creating createResNetModel1D

### ISSUE THREAD

**Issue by mg64ve** [ANTsX/ANTsRNet#10]
Hello, interesting project, thanks for sharing.
I am trying to write createResNetModel1D.
I have just taken createResNetModel2D and tried to convert to 1D layers.
I have some doubts on the following lines in squeezeAndExciteBlock2D:

```

    if( K$image_data_format() == "channels_first" )
      {
      block <- block %>% layer_permute( c( 4, 2, 3 ) )
      }
    x <- list( initial, block ) %>% layer_multiply()

```

I am using the following instead of c(4, 2, 3):

```
layer_permute( c( 4, 3 ) )
```

Not sure if it might be correct. What is the meaning of this permutation and when is supposed to be applied?

**Comment by ntustison** [comment]
@mg64ve --- good question.  Unfortunately, my experience with both the squeeze-and-excite block as well as 1-D convolutional architectures are very limited.  In fact, I haven't had a chance to test this yet.  Since the 2-D case is 

```
layer_permute( c( 4, 2, 3 ) )
```
and the 3-D case is 
```
layer_permute( c( 5, 2, 3, 4 ) )
```
I suspect the 1-D case would be 
```
layer_permute( c( 3, 2 ) )
```

but I'd have to do some more testing/thinking to be sure.

**Comment by mg64ve** [comment]
Thanks @ntustison 
It seems to work.
If I have time to document and add an example I will create a pull request, I guess it might be useful for someone else.
However now I would like to transform createResNetModel1D 1D ResNet CNN neural network model in an autoencoder.
Any good idea on how to make it?

**Comment by ntustison** [comment]
Sorry, I don't.  We have a couple of autoencoder code snippets but I haven't translated any of them to 1-D.

**Comment by mg64ve** [comment]
Ok @ntustison , but do you have 2D or 3D resnet autoencoder?

**Comment by ntustison** [comment]
No, we don't have that architecture implemented.
