### ISSUE TITLE
Loss functions

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTsRNet#3]
Hey @stnava ,

I'm thinking of a small reorganization involving pulling the various custom loss functions from their respective utilities .R files and putting them in their own file.  Would you have any issue with that?

Nick

**Comment by stnava** [comment]
that sounds good - it would be nice if they were collected somewhere .....
thx for the new pearson function.

brian

**Comment by ntustison** [comment]
Great.  Thanks.  Will do.

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTsRNet/commit/a2820afea3107bcc9d8209b2033dd2e5c8d4703e
