### ISSUE TITLE
3D image dataset for a tutorial of image segmentation

### ISSUE THREAD

**Issue by kumeS** [ANTsX/ANTsRNet#35]
Do you have any 3D image dataset and codes as a tutorial of 3D image segmentation in this package?

I would like to check the 3D segmentation accuracy using 3D U-NET and other models in ANTsRNet, but I did not find any tutorial executable code for the 3D image segmentation in the package.

It would be helpful to get some advice.

Thank you.

Satoshi.

**Comment by ntustison** [comment]
Sufficiently large datasets are difficult to obtain and are not part of this project.  You would have to do that separate from the code we've written this project.   However, you can read about one project involving 3-D segmentation using ANTsRNet [here](https://www.medrxiv.org/content/10.1101/2020.10.19.20215392v1).
