### ISSUE TITLE
Instructions for deepFlash and deepAtropos

### ISSUE THREAD

**Issue by s-j-choi** [ANTsX/ANTsRNet#36]
Dear ANTsRNet experts,

I wonder if there are examples/instructions for viewing (and saving as nii.gz) deepFlash and deepAtropos results?
I tried but I could not locate them in the manual link.

Thank you in advance.

**Comment by ntustison** [comment]
Saving:  ``?antsImageWrite``

Viewing:  [itksnap](http://www.itksnap.org/pmwiki/pmwiki.php) is a recommended .nii.gz viewer.

**Comment by s-j-choi** [comment]
Thank you. It works great!
