### ISSUE TITLE
Remove unnecessary code?

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTsRNet#38]
Hey @stnava,

Do you mind if I remove these two functions?

https://github.com/ANTsX/ANTsRNet/blob/master/R/resampleTensorUtilities.R#L40

https://github.com/ANTsX/ANTsRNet/blob/master/R/resampleTensorUtilities.R#L143

I wrote them when I was learning about this stuff and I don't think they're practically useful as they're not formulated as custom layers.  Also, with the changes I'm making, I'd rather not propagate those edits to these, IMO, obsolete functions.

**Comment by stnava** [comment]
no problem

**Comment by ntustison** [comment]
Thanks.
