### ISSUE TITLE
Cortical thickness: Error in atropos$probabilityImages[[4]] + atropos$probabilityimages[[5]] : 

### ISSUE THREAD

**Issue by JinFeng-Wu** [ANTsX/ANTsRNet#46]
Hi, I run this:
library(ANTsRNet)
library(ANTsR)
library(keras)
t1 <- antsImageRead('t1_test.nii')
ct <- corticalThickness(t1, antsxnetCacheDirectory = './', verbose = TRUE)

which produce an error:
=============================================================================
The composite transform comprises the following transforms (in order): 
  1. inverse of /var/folders/k6/j4kr_q3s5w345njb9dbh1v5m0000gn/T//RtmpVKxCUD/file1484265f99ab0GenericAffine.mat (type = AffineTransform)
=============================================================================
Default pixel value: 0.0000e+00
Interpolation type: LinearInterpolateImageFunction
Output warped image: 0x7ffb5e6175d0
Error in atropos$probabilityImages[[4]] + atropos$probabilityimages[[5]] : 
  non-numeric argument to binary operator

#######
I've tested the pipeline on two computer, which all produced this error, can you help to fix this?

Thank you.

**Comment by ntustison** [comment]
Thanks for this.  I just pushed a fix.  Can you update your repo and try it again?

**Comment by JinFeng-Wu** [comment]
Thank you very much for your help~
