### ISSUE TITLE
Huge memory usage after using desikanKillianyTourvilleLabeling()

### ISSUE THREAD

**Issue by JinFeng-Wu** [ANTsX/ANTsRNet#48]
Hi there.
After I ran dkt <- desikanKillianyTourvilleLabeling(T1), it apeared that the memory was up to 22GB for a single run, even after I ran rm(list = ls()). 
Further more, if I looped subjects using this function, the memory would be accumulated and finally caused memory failure. I guess the problem might be the parameters of the deep learning model?
Can you help to check it out, solutions will be much appreciated.
Thank you!

**Comment by ntustison** [comment]
Yep, that’s known.  You’re welcome to try the python version which I use on my cluster with allocation of 18gb.

**Comment by JinFeng-Wu** [comment]
Thank you, I've tried ANTsPy, it worked fine.

**Comment by ntustison** [comment]
Please close any issue that has been adequately addressed.
