### ISSUE TITLE
Cortical thickness evaluation inconsistency!!!

### ISSUE THREAD

**Issue by JinFeng-Wu** [ANTsX/ANTsRNet#49]
Hi there. I tried two versions cortical thickness evaluation methods, python one and R one. It turned out the evaluated thickness varied in two approaches. I think this could be the difference of probability maps evaluation in two sessions of deep atropos? How can I fix this?

**Comment by JinFeng-Wu** [comment]
The thickness varied in a great deal, for example, the max thickness of python version is around 8, and 5 for the R one. Also, the distribution of thickness of all voxels differed greatly.

**Comment by ntustison** [comment]
I just ran the following two snippets:

```
> library( ANTsR )
> library( ANTsRNet )
> t1 <- antsImageRead(getANTsXNetData("kirby"))
> kk <- corticalThickness( t1, verbose = TRUE )
> antsImageWrite( kk$thicknessImage, "~/Desktop/kkR.nii.gz" )
```

and 

```
>>> import ants
>>> import antspynet
>>> t1 = ants.image_read(antspynet.get_antsxnet_data("kirby"))
>>> kk = antspynet.cortical_thickness(t1, verbose=True)
>>> ants.image_write(kk['thickness_image'], "~/Desktop/kkPy.nii.gz")
```

and the differences were negligible between the two output images.

**Comment by JinFeng-Wu** [comment]
Thank you for your help. I tested one more time, and the results were quite similar.
By the way, I fed the segments generated by deep atropos into the SHELL kellykapowski, the results were substantially different from the results produced by R or python, why is that? Is the algorithm different in these approaches?

**Comment by ntustison** [comment]
> Is the algorithm different in these approaches?

No.  My guess is that you didn't set up the priors properly in the input to ``KellyKapowski``.  Take a look at the ``antsCorticalThickness.sh`` script.

**Comment by JinFeng-Wu** [comment]
library( ANTsR )
library( ANTsRNet )
t1 <- antsImageRead(getANTsXNetData("kirby"))
atropos <- deepAtropos( t1, doPreprocessing = TRUE,
                         verbose = TRUE )
# Kelly Kapowski cortical thickness
kkSegmentation <- antsImageClone(atropos$segmentationImage)
kkSegmentation[kkSegmentation == 4] <- 3
grayMatter <- atropos$probabilityImages[[3]]
whiteMatter <- atropos$probabilityImages[[4]] + atropos$probabilityImages[[5]]
kk <- kellyKapowski( s = kkSegmentation, g = grayMatter, w = whiteMatter,
                     its = 45, r = 0.025, m = 1.5 )
antsImageWrite(kk,'ct.nii.gz')
antsImageWrite(grayMatter,'gm.nii.gz')
antsImageWrite(whiteMatter,'wm.nii.gz')
antsImageWrite(kkSegmentation, 'segment.nii.gz')
antsImageWrite(t1,'t1.nii.gz')

## save out the segmentation, gray matter, and white matter, and run shell KK
KellyKapowski -d 3 -s segment.nii.gz -g gm.nii.gz -w wm.nii.gz -o ct_shell.nii.gz 

I really don't think that I set up the parameters wrong right now, but results are still substantially different.

**Comment by ntustison** [comment]
Are the parameters defaulting to the same value?  Did you compare the written output?

**Comment by JinFeng-Wu** [comment]
I did compare the outpputs, and quite confident that the parameters were set to the default. I've tested a lot, the results differed substantially.

**Comment by ntustison** [comment]
Then please neatly organize a complete example including the input images, deep atropos output (segmentation and priors), the antsrnet/antspynet thickness image, the shell script ``KellyKapowski`` output, and the command script you used to generate the output.

**Comment by JinFeng-Wu** [comment]
Hi Nick, I already sent you a email with those files and outputs to your gmail address, please check it out.

**Comment by ntustison** [comment]
Okay, I explicitly asked you to check the parameters "(Are the parameters defaulting to the same value?  Did you compare the written output?)" and I also told you to check the ``antsCorticalThickness.sh`` script so I assumed you had checked the parameters.  However, it would seem you did not do that.   Please help us by doing your part in investigating the issues especially if you're trying to do something that's not a traditional use of the software.

The ``KellyKapowski`` call for the ANTsRNet command is 

```
kk <- kellyKapowski( s = kkSegmentation, g = grayMatter, w = whiteMatter, its = 45, r = 0.025, m = 1.5 )
```

The first thing you notice is that you forgot to explicitly set certain parameters with your call:

```
KellyKapowski -d 3 -s segment.nii.gz -g gm.nii.gz -w wm.nii.gz -o ct_shell.nii.gz
```

Also, If you compare the output log with how you called it, you'll see that they're very different and its due to parameter choice (as I mentioned above).   

Here are the parameters for the KellyKapowski call that you should use in your experiment:  

https://github.com/ANTsX/ANTs/blob/master/Scripts/antsCorticalThickness.sh#L400-L405

**Comment by JinFeng-Wu** [comment]
Thank you very much for your help. It was my serious mistake not to notice the parameters differences, sorry for the trouble.
After I adjusted my shell KellyKapowski parameters, which were:
     `KellyKapowski -d 3 -s segment.nii.gz -g gm.nii.gz -w wm.nii.gz -o ct_shell.nii.gz -v 1 -c [45, 0.0, 10] -m 1.5 -r 0.025 -t 10 `

     Maximum number of iterations = 45
     Thickness prior estimate = 10
     Smoothing variance = 1
     Smoothing velocity field variance = 1.5
     Number of integration points = 10
     Maximum number of invert displacement field iterations = 20
     Initial gradient step = 0.025
     Current gradient step = 0.025
     Convergence threshold = 0
     Convergence window size = 10
     Time smoothing variance = 1

ANTsR codes are still:
`kk <- kellyKapowski( s = kkSegmentation, g = grayMatter, w = whiteMatter, its = 45, r = 0.025, m = 1.5 )
`
I think these parameters were matched up with the KellyKapowski in ANTsR, I made lots of comparisons with the default setting of KellyKapowski in ANTsR and shell parameters, I don't think there are some substantial differences right now, but the results still differed a lot. I wish I made a mistake again. Did I miss someting important again? 
I notice that there is an option `matrix-based smoothing` in ANTsR, I didn't find such an option in shell, does it matter?

**Comment by ntustison** [comment]
Okay, send me the screen dumps for both versions (ANTsRNet and shell).

**Comment by MichaelWu-21** [comment]
Hi Nick, I tested the ANTsR and shell with the same segmentation, gray matter and white matter, here are the results:

`KellyKapowski -d 3 -s C0_001_segment.nii.gz -g C0_001_graymatter.nii.gz -w C0_001_whitematter.nii.gz -o ct_shell.nii.gz -c '[45,' 0.0, '10]' -m 1.5 -r 0.025 -t 10 -n 10 -v 1`

Running DiReCT for 3-dimensional images.

  Iteration 1 (of 45).  Current energy = 0.798754.  
  Iteration 2 (of 45).  Current energy = 0.721735.  
  Iteration 3 (of 45).  Current energy = 0.678374.  
  Iteration 4 (of 45).  Current energy = 0.649241.  
  Iteration 5 (of 45).  Current energy = 0.631665.  
  Iteration 6 (of 45).  Current energy = 0.61938.  
  Iteration 7 (of 45).  Current energy = 0.610855.  
  Iteration 8 (of 45).  Current energy = 0.603332.  
  Iteration 9 (of 45).  Current energy = 0.598265.  
  Iteration 10 (of 45).  Current energy = 0.593837.  (convergence value = 0.016835, threshold = 0)
  Iteration 11 (of 45).  Current energy = 0.590738.  (convergence value = 0.0102212, threshold = 0)
  Iteration 12 (of 45).  Current energy = 0.588146.  (convergence value = 0.00661771, threshold = 0)
  Iteration 13 (of 45).  Current energy = 0.585658.  (convergence value = 0.00448223, threshold = 0)
  Iteration 14 (of 45).  Current energy = 0.583882.  (convergence value = 0.00320135, threshold = 0)
  Iteration 15 (of 45).  Current energy = 0.582554.  (convergence value = 0.00234827, threshold = 0)
  Iteration 16 (of 45).  Current energy = 0.581097.  (convergence value = 0.00176439, threshold = 0)
  Iteration 17 (of 45).  Current energy = 0.579709.  (convergence value = 0.00134336, threshold = 0)
  Iteration 18 (of 45).  Current energy = 0.578594.  (convergence value = 0.00105847, threshold = 0)
  Iteration 19 (of 45).  Current energy = 0.57757.  (convergence value = 0.000848367, threshold = 0)
  Iteration 20 (of 45).  Current energy = 0.576622.  (convergence value = 0.000701619, threshold = 0)
  Iteration 21 (of 45).  Current energy = 0.575545.  (convergence value = 0.000593279, threshold = 0)
  Iteration 22 (of 45).  Current energy = 0.57474.  (convergence value = 0.000508784, threshold = 0)
  Iteration 23 (of 45).  Current energy = 0.574047.  (convergence value = 0.00044702, threshold = 0)
  Iteration 24 (of 45).  Current energy = 0.573474.  (convergence value = 0.000393325, threshold = 0)
  Iteration 25 (of 45).  Current energy = 0.573077.  (convergence value = 0.000338316, threshold = 0)
  Iteration 26 (of 45).  Current energy = 0.572543.  (convergence value = 0.000290684, threshold = 0)
  Iteration 27 (of 45).  Current energy = 0.572047.  (convergence value = 0.000251159, threshold = 0)
  Iteration 28 (of 45).  Current energy = 0.571586.  (convergence value = 0.000216633, threshold = 0)
  Iteration 29 (of 45).  Current energy = 0.571145.  (convergence value = 0.00018737, threshold = 0)
  Iteration 30 (of 45).  Current energy = 0.570782.  (convergence value = 0.000162424, threshold = 0)
  Iteration 31 (of 45).  Current energy = 0.570439.  (convergence value = 0.000144966, threshold = 0)
  Iteration 32 (of 45).  Current energy = 0.570177.  (convergence value = 0.000130232, threshold = 0)
  Iteration 33 (of 45).  Current energy = 0.569868.  (convergence value = 0.000118121, threshold = 0)
  Iteration 34 (of 45).  Current energy = 0.569447.  (convergence value = 0.000109171, threshold = 0)
  Iteration 35 (of 45).  Current energy = 0.569196.  (convergence value = 9.88332e-05, threshold = 0)
  Iteration 36 (of 45).  Current energy = 0.568962.  (convergence value = 8.96283e-05, threshold = 0)
  Iteration 37 (of 45).  Current energy = 0.568733.  (convergence value = 8.15397e-05, threshold = 0)
  Iteration 38 (of 45).  Current energy = 0.568518.  (convergence value = 7.43744e-05, threshold = 0)
  Iteration 39 (of 45).  Current energy = 0.568348.  (convergence value = 6.77496e-05, threshold = 0)
  Iteration 40 (of 45).  Current energy = 0.568165.  (convergence value = 6.13507e-05, threshold = 0)
  Iteration 41 (of 45).  Current energy = 0.568014.  (convergence value = 5.50722e-05, threshold = 0)
  Iteration 42 (of 45).  Current energy = 0.567825.  (convergence value = 4.88429e-05, threshold = 0)
  Iteration 43 (of 45).  Current energy = 0.567659.  (convergence value = 4.33204e-05, threshold = 0)
  Iteration 44 (of 45).  Current energy = 0.567506.  (convergence value = 4.0055e-05, threshold = 0)
  Iteration 45 (of 45).  Current energy = 0.567428.  (convergence value = 3.64957e-05, threshold = 0)
   ImageToImageFilter (0x5613f38131c0)
     RTTI typeinfo:   itk::DiReCTImageFilter<itk::Image<unsigned int, 3u>, itk::Image<float, 3u> >
     Reference Count: 1
     Modified Time: 439579
     Debug: Off
     Object Name: 
     Observers: 
       IterationEvent(Command)
     Inputs: 
       Primary: (0x5613f381f580) *
       _1: (0x5613f381fae0)
       _2: (0x5613f3825460)
     Indexed Inputs: 
       0: Primary (0x5613f381f580)
       1: _1 (0x5613f381fae0)
       2: _2 (0x5613f3825460)
     Required Input Names: Primary
     NumberOfRequiredInputs: 3
     Outputs: 
       Primary: (0x5613f384ef70)
       _1: (0x5613f38d8910)
     Indexed Outputs: 
       0: Primary (0x5613f384ef70)
       1: _1 (0x5613f38d8910)
     NumberOfRequiredOutputs: 1
     Number Of Work Units: 128
     ReleaseDataFlag: Off
     ReleaseDataBeforeUpdateFlag: Off
     AbortGenerateData: Off
     Progress: 0
     Multithreader: 
       RTTI typeinfo:   itk::PoolMultiThreader
       Reference Count: 1
       Modified Time: 189
       Debug: Off
       Object Name: 
       Observers: 
         none
       Number of Work Units: 128
       Number of Threads: 80
       Global Maximum Number Of Threads: 128
       Global Default Number Of Threads: 80
       Global Default Threader Type: itk::MultiThreaderBaseEnums::Threader::Pool
       SingleMethod: 0
       SingleData: 0
     DynamicMultiThreading: On
     CoordinateTolerance: 1e-06
     DirectionTolerance: 1e-06
     Gray matter label = 2
     White matter label = 3
     Maximum number of iterations = 45
     Thickness prior estimate = 10
     Smoothing variance = 1
     Smoothing velocity field variance = 1.5
     Number of integration points = 10
     Maximum number of invert displacement field iterations = 20
     Initial gradient step = 0.025
     Current gradient step = 0.025
     Convergence threshold = 0
     Convergence window size = 10
     Time smoothing variance = 1
DiReCT elapsed time: 2261.54

ANTsR test:
`seg <- antsImageRead('C0_001_segment.nii.gz')
gm <- antsImageRead('C0_001_graymatter.nii.gz')
wm <- antsImageRead('C0_001_whitematter.nii.gz')
kk <- kellyKapowski( s = seg, g = gm, w = wm, its = 45, r = 0.025, m = 1.5 , verbose = TRUE)`

Loading required package: ANTsRCore

Attaching package: ‘ANTsRCore’

The following objects are masked from ‘package:stats’:

    sd, var

The following objects are masked from ‘package:base’:

    all, any, apply, max, min, prod, range, sum

Running DiReCT for 3-dimensional images.

  Iteration 1 (of 45).  Current energy = 0.798754.  
  Iteration 2 (of 45).  Current energy = 0.702359.  
  Iteration 3 (of 45).  Current energy = 0.630685.  
  Iteration 4 (of 45).  Current energy = 0.576393.  
  Iteration 5 (of 45).  Current energy = 0.537182.  
  Iteration 6 (of 45).  Current energy = 0.506531.  
  Iteration 7 (of 45).  Current energy = 0.484202.  
  Iteration 8 (of 45).  Current energy = 0.466116.  
  Iteration 9 (of 45).  Current energy = 0.452721.  
  Iteration 10 (of 45).  Current energy = 0.441572.  (convergence value = 0.0375215, threshold = 0)
  Iteration 11 (of 45).  Current energy = 0.432227.  (convergence value = 0.0263518, threshold = 0)
  Iteration 12 (of 45).  Current energy = 0.42482.  (convergence value = 0.0188044, threshold = 0)
  Iteration 13 (of 45).  Current energy = 0.417821.  (convergence value = 0.0136891, threshold = 0)
  Iteration 14 (of 45).  Current energy = 0.412617.  (convergence value = 0.0101981, threshold = 0)
  Iteration 15 (of 45).  Current energy = 0.408827.  (convergence value = 0.00770925, threshold = 0)
  Iteration 16 (of 45).  Current energy = 0.404735.  (convergence value = 0.00596446, threshold = 0)
  Iteration 17 (of 45).  Current energy = 0.400892.  (convergence value = 0.00469531, threshold = 0)
  Iteration 18 (of 45).  Current energy = 0.397707.  (convergence value = 0.00377408, threshold = 0)
  Iteration 19 (of 45).  Current energy = 0.39475.  (convergence value = 0.00307333, threshold = 0)
  Iteration 20 (of 45).  Current energy = 0.392039.  (convergence value = 0.00254429, threshold = 0)
  Iteration 21 (of 45).  Current energy = 0.390006.  (convergence value = 0.00213484, threshold = 0)
  Iteration 22 (of 45).  Current energy = 0.387893.  (convergence value = 0.00180975, threshold = 0)
  Iteration 23 (of 45).  Current energy = 0.385685.  (convergence value = 0.00157581, threshold = 0)
  Iteration 24 (of 45).  Current energy = 0.384422.  (convergence value = 0.0013709, threshold = 0)
  Iteration 25 (of 45).  Current energy = 0.381765.  (convergence value = 0.00120637, threshold = 0)
  Iteration 26 (of 45).  Current energy = 0.380928.  (convergence value = 0.00105246, threshold = 0)
  Iteration 27 (of 45).  Current energy = 0.379409.  (convergence value = 0.000930632, threshold = 0)
  Iteration 28 (of 45).  Current energy = 0.378223.  (convergence value = 0.000823807, threshold = 0)
  Iteration 29 (of 45).  Current energy = 0.376929.  (convergence value = 0.000735588, threshold = 0)
  Iteration 30 (of 45).  Current energy = 0.375655.  (convergence value = 0.000665165, threshold = 0)
  Iteration 31 (of 45).  Current energy = 0.374497.  (convergence value = 0.000599649, threshold = 0)
  Iteration 32 (of 45).  Current energy = 0.373496.  (convergence value = 0.000541826, threshold = 0)
  Iteration 33 (of 45).  Current energy = 0.372354.  (convergence value = 0.000500086, threshold = 0)
  Iteration 34 (of 45).  Current energy = 0.371455.  (convergence value = 0.000452211, threshold = 0)
  Iteration 35 (of 45).  Current energy = 0.370421.  (convergence value = 0.000431482, threshold = 0)
  Iteration 36 (of 45).  Current energy = 0.369628.  (convergence value = 0.000399244, threshold = 0)
  Iteration 37 (of 45).  Current energy = 0.368755.  (convergence value = 0.000372169, threshold = 0)
  Iteration 38 (of 45).  Current energy = 0.367932.  (convergence value = 0.000344835, threshold = 0)
  Iteration 39 (of 45).  Current energy = 0.367066.  (convergence value = 0.000321604, threshold = 0)
  Iteration 40 (of 45).  Current energy = 0.366392.  (convergence value = 0.000300242, threshold = 0)
  Iteration 41 (of 45).  Current energy = 0.365622.  (convergence value = 0.00028188, threshold = 0)
  Iteration 42 (of 45).  Current energy = 0.364993.  (convergence value = 0.000262637, threshold = 0)
  Iteration 43 (of 45).  Current energy = 0.364204.  (convergence value = 0.000248628, threshold = 0)
  Iteration 44 (of 45).  Current energy = 0.36361.  (convergence value = 0.000233564, threshold = 0)
  Iteration 45 (of 45).  Current energy = 0.362972.  (convergence value = 0.00022139, threshold = 0)
   ImageToImageFilter (0x555660665d90)
     RTTI typeinfo:   itk::DiReCTImageFilter<itk::Image<unsigned int, 3u>, itk::Image<float, 3u> >
     Reference Count: 1
     Modified Time: 705992
     Debug: Off
     Object Name: 
     Observers: 
       IterationEvent(Command)
     Inputs: 
       Primary: (0x55566063a430) *
       _1: (0x55566063c620)
       _2: (0x55566068cd10)
     Indexed Inputs: 
       0: Primary (0x55566063a430)
       1: _1 (0x55566063c620)
       2: _2 (0x55566068cd10)
     Required Input Names: Primary
     NumberOfRequiredInputs: 3
     Outputs: 
       Primary: (0x5556603caae0)
       _1: (0x55565ec0ce20)
     Indexed Outputs: 
       0: Primary (0x5556603caae0)
       1: _1 (0x55565ec0ce20)
     NumberOfRequiredOutputs: 1
     Number Of Work Units: 128
     ReleaseDataFlag: Off
     ReleaseDataBeforeUpdateFlag: Off
     AbortGenerateData: Off
     Progress: 0
     Multithreader: 
       RTTI typeinfo:   itk::PoolMultiThreader
       Reference Count: 1
       Modified Time: 202
       Debug: Off
       Object Name: 
       Observers: 
         none
       Number of Work Units: 128
       Number of Threads: 80
       Global Maximum Number Of Threads: 128
       Global Default Number Of Threads: 80
       Global Default Threader Type: itk::MultiThreaderBaseEnums::Threader::Pool
       SingleMethod: 0
       SingleData: 0
     DynamicMultiThreading: On
     CoordinateTolerance: 1e-06
     DirectionTolerance: 1e-06
     Gray matter label = 2
     White matter label = 3
     Maximum number of iterations = 45
     Thickness prior estimate = 10
     Smoothing variance = 1
     Smoothing velocity field variance = 1.5
     Number of integration points = 10
     Maximum number of invert displacement field iterations = 20
     Initial gradient step = 0.025
     Current gradient step = 0.025
     Convergence threshold = 0
     Convergence window size = 10
     Time smoothing variance = 1
DiReCT elapsed time: 2836.59

**Comment by JinFeng-Wu** [comment]
Okay, I got the point now. When I call corticalThickness() in ANTsRNet, the default setting of `matrix-based smoothing` is OFF, when I call kellyKapowski() in ANTsR or ANTsPy, the `matrix-based smoothing` option is on, that's the critical difference of the results generation.

**Comment by JinFeng-Wu** [comment]
Problem solved, it's exactly a parameters setting problem. 
Thank you for your help Nick.
Brilliant software!!!

**Comment by ntustison** [comment]
Thank you for finding this parameter discrepancy.  I'll work on coordinating this parameter difference with @stnava.  Currently I'm leaning towards turning off smoothing in the ANTsPy/ANTsR versions.

**Comment by JinFeng-Wu** [comment]
Thank you Nick.

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTsR/pull/354
