### ISSUE TITLE
applyDBPN4x.R app?

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTsRNet#5]
Hey @stnava—do you think we should move ``applyDBPN4x.R`` to ANTsRNet Apps?  Correct me if I’m wrong but it looks like it’s more of an application.

**Comment by stnava** [comment]
yes - it would be and probably needs more work.   e.g. generalize beyond 4x (2x, 8x) and also more/re-training on a broader set of data.

we can leave this issue open until ready.

**Comment by stnava** [comment]
probably should also do something like:
```
output  =  superResDBPN( input, outputResolution )
```
and then auto-select the model, if not provided.   the current model will fail on small input images due to the patch size.   so we need  a cross-product of 2x,4x,8x and patch sizes trained on a variety of patch data (eg natural images, medical images, etc).

**Comment by ntustison** [comment]
Okay, sounds good.  Putting together a list of the models we need to put in the quartz queue.
