### ISSUE TITLE
Any possibility of refining DKT labels

### ISSUE THREAD

**Issue by sj-choi** [ANTsX/ANTsRNet#50]
The results seemed good, in general, without any complex parameter setup step. However, a fair amount of sulcal CSF area seemed included in the cortical GM (overestimated cortical GM). 

In the following link, I can see a few options, which are helpful, but not enough. 
https://rdrr.io/github/ANTsX/ANTsRNet/man/desikanKillianyTourvilleLabeling.html
If possible, it would be great to know any fine-tuning parameters (or options) available to refine the result of DKT labeling to deal with an over/under-estimated tissue area.

Alternatively, it would be great to have some pre- and/or post-processing options for the DKT labeling to improve the results. 

Currently, I understand that T1w is only accepted as an input image. I wonder if any other optional images can be loaded (as multiple inputs) or a single input of another contrast, such as T2 FLAIR.

Thank you,
-SC

**Comment by ntustison** [comment]
>>  However, a fair amount of sulcal CSF area seemed included in the cortical GM (overestimated cortical GM).

Has this assertion been systematically evaluated over a number of different subjects and data sets?  If so, it would be good to see the results.  Otherwise, this claim might be a bit hasty without further information.  

>> If possible, it would be great to know any fine-tuning parameters (or options) available to refine the result of DKT labeling to deal with an over/under-estimated tissue area.

There are no additional options available specific to this pipeline.  You can try coupling it with post-processing but we don't have any specific suggestions.

>> Alternatively, it would be great to have some pre- and/or post-processing options for the DKT labeling to improve the results.

Again, we would have to see that there is a _systematic_ problem to improve.

>>  Currently, I understand that T1w is only accepted as an input image. I wonder if any other optional images can be loaded (as multiple inputs) or a single input of another contrast, such as T2 FLAIR.

Training was only performed using T1-weighted images as input.

**Comment by stnava** [comment]
@ntustison I believe @sj-choi is referring to the fact that DKT doesn't explicitly do a tissue segmentation.   we believe that is fine - and we adjust for it by merging the labels with the output of a tissue segmentation.  that is a fairly clean and easy way to resolve the issue although it is true that we could make a Bayesian version that explicitly incorporates tissue priors/posteriors.

**Comment by sj-choi** [comment]
@stnava Thank you for your suggestion and for reading between the lines of what I wrote. Following your suggestion, I might need to play with DTK labels and Atropos segmentation results to refine the results.

**Comment by stnava** [comment]
`deep_atropos`
