### ISSUE TITLE
A 'tensorflow not found' error

### ISSUE THREAD

**Issue by hegde00** [ANTsX/ANTsRNet#52]
Hello,

I'm trying to familiarize myself about how ANTsRNet works. To this end, I'm trying to run some example ANTsRNet script. 

**The 'tensor flow not found' error occurs with every single one of the ANTsRNet scripts I've tried to run so far.** 

For instance, this is what happens when I try to run "ANTsRNet.quick.example.r" from https://github.com/ANTsX/ANTsPyNet/wiki/Quick-example.

The script terminates with the following tensorflow error:

Error: Python module tensorflow.keras was not found. 

This error occurs when the createUnetModel2D() call in the script is encountered (please see the attached log and the script I'm running). In **general (as far as I can tell; I'm not positive), the error seems to occur anytime anything in the keras:: domain is called either directly or through a dependent package.** But keras seems to be installed fine on my machine; for instance, library(keras) executes fine without errors.

I tried simple-minded things like
    > install.packages( "tensorflow" )
It ran without error, but the aforementioned tensorflow error still occurs.

FYI, the GPU on my laptop (Windows 11 64-bit home edition) is not set up.

Thank you,
Jay

[ANTsRNet_error.log.TXT](https://github.com/ANTsX/ANTsRNet/files/8191715/ANTsRNet_error.log.TXT)
[ANTsRNet.quick.example.r.TXT](https://github.com/ANTsX/ANTsRNet/files/8191716/ANTsRNet.quick.example.r.TXT)

**Comment by hegde00** [comment]
I was just able to fix the above problem by running the following command in R:
> install_keras()

This fix was suggested in https://stackoverflow.com/questions/44611325/r-keras-package-error-python-module-tensorflow-contrib-keras-python-keras-was-n.

With the above fix, I've now been able to run every example script in Nick Tustison's ANTsRNet GitHub (https://github.com/ntustison/ANTsRNetExamples) I've tried so far.

**Comment by ntustison** [comment]
Great.  Glad you got it to work.
