### ISSUE TITLE
ANTsRNet/ANTsPyNet approaches to image registration

### ISSUE THREAD

**Issue by hegde00** [ANTsX/ANTsRNet#55]
Hi NIck,

I'm trying to register images of _non-brain_ bodily structures. ANTsR  routines work rather well in my hands for this purpose, but not great. So I was wondering if deep learning-based (i.e., written in ANTsRNet/ANTsPyNet) solutions to image registration exist. 

I see that others have reported good success using FlowNet/FlowReg architectures implemented on non-ANTsX platforms. Some studies (e.g., Mocanu et al, 2021) even report that variations of FlowReg outperform ANTs. So I figured perhaps you and/or others have come up with ANTsRNet/ANTsPyNet DNNs that outperform FlowReg.

Best,
Jay

**Comment by ntustison** [comment]
We haven’t prioritized deep learning approaches for image registration so we don’t have anything to offer in ANTsXNet.

**Comment by hegde00** [comment]
OK Nick, thank you very much for letting me know.
