### ISSUE TITLE
Installation failed. 

### ISSUE THREAD

**Issue by sj-choi** [ANTsX/ANTsRNet#61]
ANTsR and ANTsRCore were successfully installed. However, I got the following error when I attempted to install ANTsRNet on Ubuntu 20.04. I have tried two methods. Using github (Option 1) and compiling from source (Option 2). I attached the error message from both attempts.

Option 1
> devtools::install_github("ANTsX/ANTsRNet")
Downloading GitHub repo ANTsX/ANTsRNet@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                    
2: CRAN packages only                     
3: None                                   
4: keras (2.13.0 -> b7a381d36...) [GitHub]

Enter one or more numbers, or an empty line to skip updates: 
── R CMD build ───────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/RtmpfvvnCE/remotes1d97c5cd36e60/ANTsX-ANTsRNet-ddd3d76/DESCRIPTION’ ...
─  preparing ‘ANTsRNet’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘ANTsRNet_1.1.tar.gz’
   
Installing package into ‘/home/xubuntu/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘ANTsRNet’ ...
** using non-staged installation via StagedInstall field
** R
** inst
** byte-compile and prepare package for lazy loading
Error: object ‘antsAverageImages’ is not exported by 'namespace:ANTsRCore'
Execution halted
ERROR: lazy loading failed for package ‘ANTsRNet’
* removing ‘/home/xubuntu/R/x86_64-pc-linux-gnu-library/3.6/ANTsRNet’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpfvvnCE/file1d97c1b0665b2/ANTsRNet_1.1.tar.gz’ had non-zero exit status

Option 2
(base) xubuntu@ubuntu:~$ R CMD INSTALL ANTsRNet
* installing to library ‘/home/xubuntu/R/x86_64-pc-linux-gnu-library/3.6’
* installing *source* package ‘ANTsRNet’ ...
** using non-staged installation via StagedInstall field
** R
** inst
** byte-compile and prepare package for lazy loading
Error: object ‘antsAverageImages’ is not exported by 'namespace:ANTsRCore'
Execution halted
ERROR: lazy loading failed for package ‘ANTsRNet’
* removing ‘/home/xubuntu/R/x86_64-pc-linux-gnu-library/3.6/ANTsRNet’

Please instruct me on what I should do to resolve this issue.

Best,
SC

**Comment by ntustison** [comment]
What's your ``sessionInfo()``?

**Comment by ntustison** [comment]
Actually, I updated a couple things in ANTsRNet due to some recent changes in ANTsRCore/ANTsR.  On my ubuntu machine, I was able to do a clean install of ANTsR/ANTsRCore through devtools and then a direct install of ANTsRNet and everything seems to work.  Please try again and let us know.

**Comment by sj-choi** [comment]
I attempted to install ANTsRNet on 04/06, last Saturday. I did not work. Whatever you did, it was installed well. 
Thank you!!! 

I attached the successful installation below: 
![image](https://github.com/ANTsX/ANTsRNet/assets/1088166/e0efc3bc-cfcf-48cf-b668-8c6ef639b3f4)

**Comment by sj-choi** [comment]
Installation was successful. Now, I got another issue.
https://github.com/ANTsX/ANTsRNet/issues/62
