### ISSUE TITLE
Replacing function-level antsxnetCacheDirectory

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTsRNet#69]
Analagous to PR in [ANTsPyNet](https://github.com/ANTsX/ANTsPyNet/pull/130)

Just making an issue to track some questions I have.

@ntustison in `histology.R` there are some fallbacks to a local `ANTsXNet` directory - I assume this was for testing unreleased networks. Should I clean these up or leave in place?

https://github.com/ANTsX/ANTsRNet/blob/46cff9428dd48f009e61a13807288c61b3f6e3a7/R/histology.R#L101-L104

**Comment by ntustison** [comment]
Awesome.  Thanks @cookpa .  

Yeah, please just comment out that entire function.  I don't want to get rid of it yet as the paper's not published but, outside of being able to remember what I did, it doesn't have much (if any) utility.

**Comment by cookpa** [comment]
Completed in #70
