### ISSUE TITLE
typo in alpha layer learning?

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTsRNet#7]
https://github.com/ANTsX/ANTsRNet/blob/05e3090ba58ab6d785cc474f0575a69abb26eac6/R/createDeepBackProjectionNetworkModel.R#L387

1, 2, 3   instead ?

**Comment by ntustison** [comment]
Oops, sorry, yes.

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTsRNet/commit/a5113fd6cf97f61954d10fb483890e765726cfcb
